export const GET_CONTACTS = 'GET_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const CONTACT_LOADING = 'CONTACT_LOADING';
export const CONTACT_ERROR = 'CONTACT_ERROR';
